sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with Dockerfile.dev"
  - docker build -t apeltop/docker-react-app -f Dockerfile.dev /learning/book/따라하며배우는_도커와_CI환경/ch6

script:
  - docker run -e CI=true apeltop/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success - start deploying the app"
